; Smart Bedroom Automation System - ESP32 firmware
; Group 10 - 3707ICT - Hardware & Automation Lead

[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    beegee-tokyo/DHT sensor library for ESPx@^1.19
